language: csharp  
sudo: required  
dist: trusty  
env:  
  - CLI_VERSION=latest
mono:  
  - 5.10.0
dotnet:  2.1.300
os:  
  - linux
branches:  
  only:
    - master
    - /.*/
before_script:
- chmod +x ./build.sh
script:  
  - ./build.sh
