language: csharp  
sudo: required  
dist: bionic  
env:  
  - CLI_VERSION=latest
mono: latest
dotnet:  3.0.100
os:  
  - linux
branches:  
  only:
    - master
    - /.*/
before_script:
- chmod +x ./build.sh
before_install:
  - sudo apt install nuget
script:  
  - ./build.sh
