language: csharp  
sudo: required  
dist: xenial  
env:  
  - CLI_VERSION=latest
mono: latest
dotnet:  3.0.100
os:  
  - linux
branches:  
  only:
    - master
    - /.*/
before_script:
- chmod +x ./build.sh
before_install:
  - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get update
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-2.1.202
  - sudo apt-get install dotnet-sdk-2.1.802
  - sudo apt-get install dotnet-sdk-2.2.402 
  - sudo apt install nuget
script:  
  - ./build.sh